### ISSUE TITLE
There is a problem wit [] symbols

### ISSUE THREAD

**Issue by Milen4o** [KevinJDurant/OpenTorrentSite#11]
There is a problem wit [] symbols. Just don't upload the torrent. It will be nice if you add Backend to see the traffic, the user and torrent revision to be aproved because may be a virus for the people.

**Comment by KevinJDurant** [comment]
Hi @Milen4o , can you give me more details where this causes problems? In the .torrent filename? Or in the torrent title name?

I'm not really planning on adding more content to this very old project. But I might later on if I find the time for it.

**Comment by AzukaChan** [comment]
Hi @Milen4o , there any many torrent files with '[ ]' symbols in their names. I don't think blocking torrents with that in their name is going to help with people attempting to upload viruses. At some point I might get around to adding a simple report button which alerts admins/mods or something.

For now set trusted users uploadstatus to 2 or 3 to let people know they are safe to download from.

**Comment by Milen4o** [comment]
> Hi @Milen4o , can you give me more details where this causes problems? In the .torrent filename? Or in the torrent title name?
> 
> I'm not really planning on adding more content to this very old project. But I might later on if I find the time for it.

There`s no detail. Just refresh the page whitout notification torrent uploaded and it's no registered in the database. If i try to upload it again say this torrent archive is used by another process. I need to check later why.

**Comment by AzukaChan** [comment]
@Milen4o Testing using my live site I don't seem to have any issue uploading torrents with '[ ]' in the file name or title.

A few things to check:

1) Make sure you have set the appropriate file permissions on your web server.
2) Add a "torrents" folder to the root of your site.
3) Login to MySQL phpmyadmin and delete the torrent manually from the database, this should stop the "used by another process" issue happening.
4) login to your phpmyadmin and navigate to your torrent database, select the users table and then select "structure" from the navigation bar at the top of the screen. From here you will need to set the default value of "uploaderstatus" to 0 instead of NULL.

**Comment by Milen4o** [comment]
> @Milen4o Testing using my live site I don't seem to have any issue uploading torrents with '[ ]' in the file name or title.
> 
> A few things to check:
> 
> 1. Make sure you have set the appropriate file permissions on your web server.
> 2. Add a "torrents" folder to the root of your site.
> 3. Login to MySQL phpmyadmin and delete the torrent manually from the database, this should stop the "used by another process" issue happening.
> 4. login to your phpmyadmin and navigate to your torrent database, select the users table and then select "structure" from the navigation bar at the top of the screen. From here you will need to set the default value of "uploaderstatus" to 0 instead of NULL.

Seems to work now whitout changin nothing on a hosting server. but i found another issue with the characters like ñ Ñ ó, etc but this is jus add the codificación in the code.

**Comment by KevinJDurant** [comment]
> It will be nice if you add Backend to see the traffic

You could always add your Google Analytics snippet and view the stats in the GA Dashboard instead of custom coding it for this project.

> but i found another issue with the characters like ñ Ñ ó, etc but this is jus add the codificación in the code.

It sounds like you have fixed this issue. Please open a new issue when you have other questions.
