### ISSUE TITLE
Small Update

### ISSUE THREAD

**Issue by Milen4o** [KevinJDurant/OpenTorrentSite#14]
I did an small update on that adding an Admin user and contro panel who is showing if you are admin. 
There is an little information on it like: total torrents upload. 
If you are normal user you will se total torrents upload from you. 
User data. 
And if you are admin you will see total users registered. 
![admin update](https://user-images.githubusercontent.com/21200268/67143134-7c73df80-f268-11e9-8712-918bb141cf9e.png)
Need to add update password if the user need to change it. Email confirmation is still an issue.

**Comment by AzukaChan** [comment]
You should try pulling from [my fork](https://github.com/AzukaChan/OpenTorrentSite) until Kevin merges it into the master branch. Here's an example of what the admin/user control panel looks like:

http://i.imgur.com/jXDEeEv.png
https://i.ibb.co/hZxNpsh/user.png

What you're describing has already been setup and is (for the most part) working.
You can test it here: https://github.com/AzukaChan/OpenTorrentSite

Account Uploads = Your individual torrent upload count
Total Uploads = Website Torrent Count
Total Users = Total User Count
Buttons to purge torrents, change uploaderstatus or ban user have also been added.

**Comment by Milen4o** [comment]
Did you did any changes in the DB to log in as ADMIN ¿?

**Comment by Milen4o** [comment]
Ahh okay i see you did it on another way counting the uploaderstatus 99 like ADMIN. I added admin in the database counting from 0 to 1. 0 for a normal user and 1 for an admin.

**Comment by AzukaChan** [comment]
I didn't really see the need to edit the database when there is already a value for users uploaderstatus.

Admin = 99
VIP = 3
Trusted = 2
Normal User = 1
Banned = -1

**Comment by Milen4o** [comment]
I didn't think that it can be used for admin. I was thinking for normal user, super user (Vip) but yeah same think can be don in diferent ways.

**Comment by Milen4o** [comment]
What diference will have the vip from the normal user ¿?

**Comment by AzukaChan** [comment]
> 
> 
> What diference will have the vip from the normal user ¿?


**Trusted/VIP user icons**
Changing a users uploaderstatus to 2 (trusted) or 3 (vip) will place a "trusted user" icon next to the uploader name on torrents.php indicating the user/torrent is trusted and safe to download.
![Capture](https://user-images.githubusercontent.com/42724187/67271486-f375d600-f4fd-11e9-8347-0e0cd3260f93.PNG)

**Comment by Milen4o** [comment]
Nice idea. This can be used to indicate if the torrent is safe in the index.php by adding next to the icon depending on the status (trusted torrent or user upload).

**Comment by Milen4o** [comment]
By adding that code after the line 171 index.php and afther that adding 
{
  if($row["uploaderstatus"]==3)
  {echo '<img src="/css/vip.png" alt="VIP User">'; } 
else
  if($row["uploaderstatus"]==2)
  {echo '<img src="/css/trusted.png" alt="Trusted User">'; } 
} 
you can easy show it on the first page.

**Comment by AzukaChan** [comment]
![index](https://user-images.githubusercontent.com/42724187/67354589-d4785200-f598-11e9-8726-0e304dfb4066.PNG)

This feature has now been added in the latest update. Try cloning the repo again to see whats new.
This issue can now be closed.

**Comment by Milen4o** [comment]
I am planing to add update user account information like username, email and password in case someone need it like me. Now i wanna change my username. I can go to the database but yeah no one have the knowledge and access to it.
