### ISSUE TITLE
Permission Errors Deluxe

### ISSUE THREAD

**Issue by cullen-carstens** [KevinJDurant/OpenTorrentSite#17]
Good day, I don't know if I'm the only one.

I have scoured the internet for advice to no avail.
I can't seem to figure out what's bugging out...

**Running on a Xampp Server [WIN 10]** 

- I have: 
- [ ] imported the .sql files to a DB named "torrentz" in PHPMyAdmin
- [ ] created a MySQL user and given it full priveledges on database "torrentz"
- [ ] added all the required credentials in **/config/config.ini.php**
- [ ] created an account.
- [ ] changed my **uploaderstatus** to 99-

**NOW WHEN I FILL IN ALL THE DETAILS TO UPLOAD A TORRENT**

1. The page stays on upload.php
2. I get this error:
____________________________________________________________
Warning: count(): Parameter must be an array or an object that implements Countable in I:\xampp\htdocs\php\upload.php on line 121

Fatal error: Uncaught Error: Call to undefined function Scrapeer\socket_create() in I:\xampp\htdocs\php\libs\scraper.php:442 Stack trace: #0 I:\xampp\htdocs\php\libs\scraper.php(425): Scrapeer\Scraper->udp_create_connection('tracker.openbit...', 80) #1 I:\xampp\htdocs\php\libs\scraper.php(398): Scrapeer\Scraper->prepare_udp('tracker.openbit...', 80) #2 I:\xampp\htdocs\php\libs\scraper.php(174): Scrapeer\Scraper->scrape_udp(Array, 'tracker.openbit...', 80, false) #3 I:\xampp\htdocs\php\libs\scraper.php(101): Scrapeer\Scraper->try_scrape('udp', 'tracker.openbit...', 80, '', false) #4 I:\xampp\htdocs\php\upload.php(53): Scrapeer\Scraper->scrape(Array, Array) #5 I:\xampp\htdocs\en\upload\upload.php(203): upload() #6 {main} thrown in I:\xampp\htdocs\php\libs\scraper.php on line 442
____________________________________________________________

**Running on a cPanel Server**

- I did all the same required steps.
____________________________________________________________
Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
____________________________________________________________

**I DON'T KNOW, I'VE BEEN SITTING FOR DAYS**

**Comment by cullen-carstens** [comment]
wow, I feel so stupid, changed php version to 5.5...

It seems to working now...

Touch wood 💯

**Comment by AzukaChan** [comment]
> 
> 
> wow, I feel so stupid, changed php version to 5.5...
> 
> It seems to working now...
> 
> Touch wood 💯

Yeah that would do it; I think depending on your PHP version some of the files "go missing" since it doesnt read the directory properly. Feel free to pull from my branch while Kevin refactors the voting system that I have added.

Keep in mind that some torrents may show 0 seeds/leechers if your ISP is blocking UDP requests. ubuntu has an official .torrent alternate download link with HTTP seeders which is great for testing out the upload form on this template.

**Comment by cullen-carstens** [comment]
So I went onto change-user-status.php and I get a 403 Forbidden

![change-user-status php](https://user-images.githubusercontent.com/61153377/74715326-cc86a100-525e-11ea-9cef-a814c778973c.PNG)

But funny enough, when you look at the URL in the snap above you will see, it says I'm a basic user. In the users database my uploaderstatus is 99.

**Comment by AzukaChan** [comment]
You haven't set the correct file permissions on your server.
Try changing your file permissions to '644' and your directories to '755'

**Comment by cullen-carstens** [comment]
OK, I've checked every single file and directory permission all files are '644' and all folders are '755'.

Could I ask you to have a look?

**Comment by AzukaChan** [comment]
@torrentz-interserve Are you using a shared hosting service? This could possibly be a temporary issue with your hosting provider. Additionally just for the sake of it you might want to check the database structure for the 'users' table and make sure that 'uploaderstatus' is set to 0 by default instead of NULL.

**Comment by cullen-carstens** [comment]
This is what happens when I try to make your AzukaChan account VIP status.

**Comment by cullen-carstens** [comment]
![make-azuka-vip](https://user-images.githubusercontent.com/61153377/74727028-1083a100-5273-11ea-87d5-81b147c96303.PNG)

**Comment by AzukaChan** [comment]
@torrentz-interserve Just repulled from the master branch to test on the live demo and it seems to work fine for me, this must be caused by something you've changed while editing the template. Perhaps try loading the default template to see if it works then?

Also just to be sure, are you using git pull?

**Comment by cullen-carstens** [comment]
I just extracted a fresh copy and added my database creds and still the same problem.

**Comment by cullen-carstens** [comment]
![image](https://user-images.githubusercontent.com/61153377/74729069-732a6c00-5276-11ea-8afe-bcb71e8cd415.png)

**Comment by AzukaChan** [comment]
> 
> 
> I just extracted a fresh copy and added my database creds and still the same problem.

You still have insufficient privileges? [Try pulling from this repo](https://github.com/AzukaChan/OpenTorrentSite)

**Comment by cullen-carstens** [comment]
Same story... I honestly don't know whats up...

Can I give you my login details somehow, and you can have a look?

**Comment by cullen-carstens** [comment]
Can I give you my login details somehow, and you can have a look?

**Comment by cullen-carstens** [comment]
Okay, I fixed that, but now it's printing the success message in the URL bar of browser.

Here's the file..

`<?php
    include_once "../php/libs/database.php";
    include_once "../php/libs/UserHelper.php";

    date_default_timezone_set('Europe/Brussels');

    $db = new Db();

    if (!isset($_SESSION)) {
        session_start();
    }

    $message = 'Account Status Changed: ' . UserHelper::translateUserStatus($_GET['status']);

    if (UserHelper::verifyAdministrator($db, $_SESSION['userid'], $_SESSION["key"])) {
        $query = "UPDATE users SET uploaderstatus = %d WHERE user_id = %d;";
        $result = $db->query(sprintf($query, intval($_GET['status']),intval($_GET['user_id'])));
    } else {
        $message = 'Insufficient privileges!';
    }

    header("Location: /en/view/preferences.php?msg=" . $message);`

![image](https://user-images.githubusercontent.com/61153377/74815016-02915700-532b-11ea-82d1-ad6ed1d7ced5.png)

**Comment by AzukaChan** [comment]
Have you been able to fix this issue?
If so, what was the issue?

**Comment by AzukaChan** [comment]
@torrentz-interserve 
OpenTorrentSite has recently been updated; try pulling this repo again and see if you still have these issues.
