### ISSUE TITLE
Torrents won't show up.

### ISSUE THREAD

**Issue by iA-blip** [KevinJDurant/OpenTorrentSite#18]
When I add a new torrent, it wont show up in the search or in the categories. What do you think what's the problem?

**Comment by AzukaChan** [comment]
> 
> 
> When I add a new torrent, it wont show up in the search or in the categories. What do you think what's the problem?

Heres a few things to try:
1) Try setting your PHP version (in cPanel) to 7.0+
2) Make sure all files and directories have the appropriate permissions set.
3) Look for any error log files and see if you can find the issue.

**Comment by AzukaChan** [comment]
Did this help with your issue?

**Comment by iA-blip** [comment]
> > When I add a new torrent, it wont show up in the search or in the categories. What do you think what's the problem?
> 
> Heres a few things to try:
> 
> 1. Try setting your PHP version (in cPanel) to 7.0+
> 2. Make sure all files and directories have the appropriate permissions set.
> 3. Look for any error log files and see if you can find the issue.

Sorry for not responding, I have PHP version on 7.3. All files and directories (I think atleast) have appropiate permissions. I am using infinityfree to host the website. If you want to take a look, here: http://jsfileshare.rf.gd

**Comment by AzukaChan** [comment]
Seems like your website is down. Feel free to open up another ticket if this problem persists on a different hosting provider.
