### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by dkbame** [KevinJDurant/OpenTorrentSite#19]
Hello is this still in development? I have a few things to ask/request?

**Comment by AzukaChan** [comment]
@dkbame Not exactly being worked on everyday; but if something is broken i'll fix it.
What seems to be the problem?

**Comment by AzukaChan** [comment]
@dkbame Hopefully my previous answer successfully answers your question. Please open up another ticket if you have any other questions / issues.
