### ISSUE TITLE
Access denied for user 

### ISSUE THREAD

**Issue by ghosthosting** [KevinJDurant/OpenTorrentSite#2]
PHP Warning:  mysqli::mysqli(): (28000/1045): Access denied for user '-----'@'localhost' (using password: YES) in /home/theghost/public_html/php/libs/database.php on line 16

**Comment by KevinJDurant** [comment]
Hi

Are you sure you entered the right credentials in config/config.ini.php? 
Does the user you've provided for the server have enough permissions on the database?

**Comment by lninjo123** [comment]
I have the same issue do I have to uncomment the user credentials?

**Comment by ghosthosting** [comment]
![import all -sql](https://user-images.githubusercontent.com/35425736/34992276-996b7e00-faf2-11e7-9b8f-aa1f4d622212.PNG)
Hello  Kevin
![config](https://user-images.githubusercontent.com/35425736/34992203-5c24f2b0-faf2-11e7-9cc7-b6073298abfb.PNG)
![privilleges](https://user-images.githubusercontent.com/35425736/34992269-93f65d32-faf2-11e7-9a1e-8e78a2d045d1.PNG)


i entered the right credentials in config/config.ini.php

**Comment by ghosthosting** [comment]
i'm not using ftp connection

do you think that was the problem.

and is there a way i can install this them on  WordPress?



also 
Thanks for your hard work it is much appreciated

**Comment by ghosthosting** [comment]
![dad-you-are-the-king](https://user-images.githubusercontent.com/35425736/34992799-547290fc-faf4-11e7-9329-06446db00a67.png)

**Comment by lninjo123** [comment]
thank you for the info i really apprecitate your time to explain

**Comment by KevinJDurant** [comment]
@lninjo123 Don't uncomment the credentials, it's commented for security reasons, it still gets picked up by the code.

@ghosthosting I've never tried wordpress so I can't help. Do you still have that connection issue? I think your dbname should be 'theghost_newzaz', your username 'theghost_root' and then your password.

Sorry for the late responses guys, I'm very busy IRL atm.

**Comment by ghosthosting** [comment]
Thanks Kevin everything works fine now. 

i FINALLY UPLOAD MY FIRST TORRENT.

ONLY problem that i face now .

information about  
Seeds, Leech,Download

not working.



sorry to trouble you again.

**Comment by KevinJDurant** [comment]
@ghosthosting 

The reason you might not get any seeders/leechers statistics is because your hosting doesn't support/allow UDP requests, only HTTP requests. 

Are you hosting it yourself or using a payed service?

More info on this issue: https://github.com/medariox/Scrapeer/issues/12

**Comment by ghosthosting** [comment]
Hi 
Kevin

for hosting 
i'm using a payed service.


Thanks for your support .

**Comment by KevinJDurant** [comment]
@ghosthosting 

You will need to talk to your hosting provider and ask them if they can allow the UDP protocol. Some hosting providers require you to buy a static IP or a VPS service. 

There is nothing I can do codewise to prevent this.

**Comment by ghosthosting** [comment]
understood  Kevin.

Thank You very much for your support.
