### ISSUE TITLE
Id for administrator

### ISSUE THREAD

**Issue by ghost** [KevinJDurant/OpenTorrentSite#24]
What is the ID for administratorer and can you make a seed leech so of X user just download and not uploading its stops the torrents ?

**Comment by AzukaChan** [comment]
@hbs2 Set your `uploaderstatus` to `99` in the database for administrator privilege's.
I'm not really too sure what you mean by your second question.

**Comment by ghost** [comment]
thanks can you make so invites are going to work ?

**Comment by ghost** [comment]
and the other things you dont understand that was if you can make a radio measured so if one user doenloads and not uploading the users downloads stops ? :)

**Comment by AzukaChan** [comment]
I have no plans on implementing an "Invitation System" at this time; I did think about having user registration easily opened/closed from the Admin Control Panel, but I never got around to it.

To answer your second question, that seems like it would be a pretty difficult (or impossible) task without also having your own private tracker; which OpenTorrentSite does not supply. You could implement something like that if you have the time/skill in PHP.

**Comment by ghost** [comment]
thats sad a (invitation system) coud be nice :) 

i will try to inplement it :)

**Comment by AzukaChan** [comment]
@hbs2 Star this repo and keep up to date on future commits; you never know what might get added.
Feel free to open up another ticket if there is an issue.
