### ISSUE TITLE
Oops! 404 Not Found

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#25]
Hello All 

I hope that you're in good condition, I am interested in your repository opentorrentsite in GitHub.
I want to deploy it in my domain and develop it (like adding chat, donate, badges for users, torrent display photo, etc. ..), but before that I want to see it operational, I deployed it on my webserver (online) but when i try to upload a torrent, a message push up:
Oops!
404 Not Found

and I am really don't know why, I tried everything related with folder permissions (torrents folder) but worthless.
I give permission to (www-data user) ! (MySQL user) ! (chmod -R 777) and nothing succeeded.
I want your help since I am new with this problem.

Thank you in advance.

**Comment by AzukaChan** [comment]
Hi @alwisiax 

Firstly,
1. Users already have badges. 
(unless your talking about some kind of achievement system? In which case no)

2. You can add a display photo to torrents by uploading an image in to your comment when uploading a torrent.

3. There is already a comment system, not too sure why you'd want a live chat on a torrent site.

In regards to your 404 problem,
1. It seems you may have missed something during the setup process.
You need to create a folder called "torrents" in the root directory of your webspace. [Please refer to the guide on the main page](https://github.com/KevinJDurant/OpenTorrentSite#setup).

2. Make sure your webspace is running on php 7.0+

3. Install the database for OpenTorrentSite using "OpenTorrentSite.sql"
The other SQL files are currently outdated.
