### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#26]
Hello All 

I hope that you're in good condition, I am interested in your repository opentorrentsite.
I want to deploy it in my domain and develop it (like adding chat, donate, badges for users, torrent display photo, etc. ..), but before that I want to see it operational, I deployed it on my webserver (online) but when i try to upload a torrent, a message push up:
Oops! 404 Not Found
and I am really don't know why, I tried everything related with folder permissions (torrents folder) but worthless.
I give permission to (www-data user) ! (MySQL user) ! (chmod -R 777) and nothing succeeded.
I want your help since I am new with this problem.

Thank you in advance.

**Comment by AzukaChan** [comment]
Hi @alwisiax 

Firstly,
1. Users already have badges. 
(unless your talking about some kind of achievement system? In which case no)

2. You can add a display photo to torrents by uploading an image in to your comment when uploading a torrent.

3. There is already a comment system, not too sure why you'd want a live chat on a torrent site.

In regards to your 404 problem,
1. It seems you may have missed something during the setup process.
You need to create a folder called "torrents" in the root directory of your webspace. [Please refer to the guide on the main page](https://github.com/KevinJDurant/OpenTorrentSite#setup).

2. Make sure your webspace is running on php 7.0+

3. Install the database for OpenTorrentSite using "OpenTorrentSite.sql"
The other SQL files are currently outdated.

**Comment by AzukaChan** [comment]
Let me know if any of these things worked for you @alwisiax

**Comment by alwisiax** [comment]
Hello AzukaChan, I did all but problem still, the problem is here
header("Location: ../view/torrent.php?hash=".$hash[0]."&id=".$userid);
in upload.php
client browser send error that it cant find this page with this customized header.
I tried to enable rewrite module in apache also, but problem still.
have you any explanation?
-Thanks.

**Comment by AzukaChan** [comment]
When do you receive this error? When trying to upload a torrent?

Did you drop all of your database tables and reinstall using "OpenTorrentSite.sql" ?

**Comment by alwisiax** [comment]
Yes I dropped old tables and reimport using main sql file, I traced code for ex: I wrote exit; before this line and found the torrent uploaded successfully to /torrents folder but the torrent informations not added to database (torrent table).

**Comment by AzukaChan** [comment]
> Yes I dropped old tables and reimport using main sql file, I traced code for ex: I wrote exit; before this line and found the torrent uploaded successfully to /torrents folder but the torrent informations not added to database (torrent table).

Are you using XAMPP to test or a live webspace?

**Comment by alwisiax** [comment]
I test on live web space, I have a dedicated   server (not shared) with Ubuntu 18.04 OS (I installed) with all prerequisites.

**Comment by alwisiax** [comment]
I noted that when I removed if(count(torrent) == 0)
torrent.php is opened but without data! So I think the issue in insert statement in upload.php

![image](https://user-images.githubusercontent.com/73487018/98224153-cd31a580-1f5b-11eb-9f55-c70b0c308644.jpeg)

**Comment by AzukaChan** [comment]
@alwisiax 
I have re-pulled this repo and reinstalled OpenTorrentSite on my own live webspace and it seems to be working for me. I am able to register an account, upload torrents, access admin control panel, etc... My server is Windows/cPanel based so I have never tested on an Ubuntu server. Can't imagine why that would make any difference though.

If you could provide a picture, that would be helpful.

**Comment by AzukaChan** [comment]
@alwisiax 
Please re-pull the repo and install a fresh copy of OpenTorrentSite on your webspace.

It is possible to receive a "404 error! Oops!" when your server has a high latency and is having trouble processing the upload. If you notice you're receiving 404 errors, try waiting a few hours and upload the torrent again..

**Comment by alwisiax** [comment]
Finally I get results, I added insert public function to the database.php then I call it from the db object by sending the query as parameter:
![image](https://user-images.githubusercontent.com/73487018/98293521-224ed500-1fb7-11eb-932a-62a2cfa5468a.jpeg)

**Comment by alwisiax** [comment]
Finally I get results, I added insert public function to the database.php then I call it from the db object by sending the query as parameter:
![image](https://user-images.githubusercontent.com/73487018/98293703-7063d880-1fb7-11eb-909e-22f449329075.jpeg)

**Comment by AzukaChan** [comment]
@alwisiax Not sure why adding this would help, but I'm glad it does.
Unless there is a difference between Ubuntu and Windows server I can't see why the code from this repo won't work for you.

**Comment by AzukaChan** [comment]
@alwisiax When you upload a torrent, is your seed/peer data scraping successfully?

**Comment by alwisiax** [comment]
Yes, I downloaded the torrent content successfully from another peer but the new seeder not added (not counted) to the torrent stats may be because I tested from one network(same global IP address).

**Comment by AzukaChan** [comment]
I believe this issue has been resolved? Feel free to reopen another ticket if the issue persists.
