### ISSUE TITLE
Case Sensitive Search !

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#28]
if you have stored a torrent with a name like "Real Madrid" and you want to search the database for a torrent with that name you will type "real madrid" in search bar, unfortunately nothing will appear in the search result. you should type "Real Madrid" to get that torrent. searching should be not case sesitive.

**Comment by AzukaChan** [comment]
This seems to be an issue with your webspace. Testing on my server torrent searches are not case sensitive.
![nope](https://user-images.githubusercontent.com/42724187/98434268-fac44d80-2119-11eb-910d-4b377979d9b0.PNG)

If the problem still persists try add full text search to the `name` column in the `torrents` table using PhPmyAdmin and then added new torrents.

**Comment by alwisiax** [comment]
ok, another related issue: try to search using "test" word not "test torrent", is the result same?

**Comment by alwisiax** [comment]
sorry, you are right, its my side problem, I modified the code when I was testing torrent upload, when I restore the code, it is fixed.
