### ISSUE TITLE
Seeders refresh button disappeared automatically

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#29]
refresh button disappeared after one click or two, I don't know why?

**Comment by AzukaChan** [comment]
@alwisiax 
This is to prevent people from spamming the refresh button and having your IP address blacklisted from trackers and will reappear in 24 hours after being refreshed. This is a feature, not a bug.

**Comment by AzukaChan** [comment]
After testing this for myself; it seems I somehow managed to break this while developing the comment section and the button does not reappear after 24 hours. I will reopen this issue for now until I have fixed the "refresh button".

**Comment by alwisiax** [comment]
yes, but somehow it should be refreshed behind the scene, isn't it? without users intervention.

**Comment by AzukaChan** [comment]
You could easily make that change if you wanted to, but having a "refresh button" reduces server load for webspaces with a large amount of torrents in the database. Most people will hit the refresh button when its available to get the latest data anyways, you might as well save yourself some server usage.

By default this is not meant to be done "behind the scenes", having users manually refresh seed/peer data is the correct behavior.

**Comment by alwisiax** [comment]
(is not meant to be done "behind the scenes")
it can be added as an option in the configuration file, so administrator can enable/disable it depending on
his server specifications, if server can do that for me time by time why not? seed/leech count will be updated every time the torrent is downloading or finished (Seeding).

**Comment by AzukaChan** [comment]
Am an idiot; while I was testing I used the wrong Unix timestamp which prevent the button from reappearing.
This feature is working as expected.
