### ISSUE TITLE
Search for all torrent in a category!

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#30]
if I pressed search button without entering any text in search bar, it should fetch all torrents in that category.
for "anything" option, it should fetch all torrents in the site.

**Comment by AzukaChan** [comment]
There is already a category search which can be accessed by pressing on a category from the main page...
![software](https://user-images.githubusercontent.com/42724187/98454616-432f4a00-21b2-11eb-8540-5f8fa00f50bd.png)

by default there are 10 torrents per page in category view.
