### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#31]
in registration process, if I entered ahmad@abcd.com, it will be accepted. it is better to validate
the domain name of mail server such as yahoo, Gmail, Hotmail, windows live, live, outlook, etc. ..
so users shouldn't enter their business email (its temporary valid only while they are in their job position), only personal emails are permitted.

other solution: **add update info page**.

**Comment by AzukaChan** [comment]
If users are silly enough to add their business emails to a torrent site; that seems like their problem.
I have no plans on adding email verification / invitation system at this time.

Eventually users will be able to change their email from the account control panel, however this has not been implemented yet.
