### ISSUE TITLE
Traffic Capture

### ISSUE THREAD

**Issue by alwisiax** [KevinJDurant/OpenTorrentSite#32]
is there a way to capture torrents traffic in the web site?
how could we add announce URL for uploaded torrents (php/upload.php), so if anyone
downloaded a torrent, then we can capture uploaded data from (seeder) to him (peer).
this measure is very important to show the amount of total traffic of the tracker in the main page.

**Comment by AzukaChan** [comment]
You do not need your own torrent tracker to have seed/peer data appear.
As long as the trackers within the torrent file you are trying to upload are working the seed/peer data will appear.

If your webspace is showing 0seeds/0peers, your host may be blocking UDP requests.
Try uploading a torrent with HTTPS trackers and see if you get a different result.

![data](https://user-images.githubusercontent.com/42724187/98454520-0adb3c00-21b1-11eb-9af4-415708a1bafa.PNG)

**Comment by alwisiax** [comment]
![image](https://user-images.githubusercontent.com/73487018/98455440-4f4ae580-2179-11eb-8dd7-fa063c23bbaf.png)
