### ISSUE TITLE
Excessive Torrent Files May Result In 404 (Fixed)

### ISSUE THREAD

**Issue by AzukaChan** [KevinJDurant/OpenTorrentSite#33]
Only just noticed while doing my latest round of testing that when uploading torrents with upwards of 15+ trackers (number may vary, some have 100+) for whatever reason may result in a 404 error, while torrents with 5 or less trackers load perfectly including seed/peer data.

I plan on fixing this at some point, but thought I would open the issue for anyone else experiencing a similar issue.

**Comment by alwisiax** [comment]
I didn't tested for this issue, but Try to open a range of UDP ports on server firewall and find a way to make them available for torrent protocol, I think this will make a difference! because the symptom is talking about (The number of trackers).

![image](https://user-images.githubusercontent.com/73487018/98991058-fb068380-2533-11eb-9a03-b769f6dc3196.png)

**Comment by alwisiax** [comment]
Did you configured your testing on https or http?
if you use http then some of https tracker will reject sending seed/peer data because the communication with you is not encrypted and vise versa.

check this:
https://stackoverflow.com/questions/29726692/why-cant-torrent-traffic-be-encrypted

**Comment by AzukaChan** [comment]
This is for all torrents with a large amount of trackers; UDP, HTTP and HTTPS.
It has nothing to do with encrypting torrent traffic.

Excessive trackers on a torrent may result in a `Oops! 404 Error!` when attempting to upload a torrent. DHT based scraping is not supported, so if your torrent has no trackers (check the end of magnet link for `&tr=`) you may notice your seed / peer data stays at 0.

**Comment by AzukaChan** [comment]
@alwisiax This bug has been fixed! Try reinstalling OpenTorrentSite and uploading your torrents!

**Comment by alwisiax** [comment]
Good job AzukaChan.
