### ISSUE TITLE
When I was trying to upload, it's showing error.

### ISSUE THREAD

**Issue by sora59** [KevinJDurant/OpenTorrentSite#35]
Fatal error: Uncaught mysqli_sql_exception: Unknown column '70434f546d98048d624bc35c074cb5d8' in 'where clause' in C:\xampp\htdocs\php\libs\database.php:38 Stack trace: #0 C:\xampp\htdocs\php\libs\database.php(38): mysqli->query('SELECT `user_id...') #1 C:\xampp\htdocs\php\libs\database.php(51): Db->query('SELECT `user_id...') #2 C:\xampp\htdocs\php\upload.php(120): Db->select('SELECT `user_id...') #3 C:\xampp\htdocs\php\upload.php(40): valid_user('70434f546d98048...', '1', Object(Db)) #4 C:\xampp\htdocs\en\upload\upload.php(218): upload() #5 {main} thrown in C:\xampp\htdocs\php\libs\database.php on line 38

**Comment by AzukaChan** [comment]
Try following the setup instructions:
1. Copy & Paste all files to your webspace.
2. Set your webspace to PHP Version 7.0.
3. Create a folder called "torrents" in the root directory.
4. Setup a new MySQL database. For security purposes you should create a user with appropriate permissions.
5. Change the database credentials and website identification inside 'config/config.ini.php'.
6. Import "opentorrentsite.sql" from the 'sql' folder.

**Comment by AzukaChan** [comment]
Has your issue been resolved?
